name: Semgrep SAST

on:
  push:

jobs:
  semgrep-scan:
    name: Run Semgrep SAST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Semgrep
        uses: returntocorp/semgrep-action@v1.44.0
        with:
          config: p/default
